AWSTemplateFormatVersion: version date

Description: String

Metadata: template metadata

Parameters: set of parameters

Rules: set of rules

Mappings: set of mappings

Conditions: set of conditions

Transform: set of transforms

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"

Outputs: set of outputs
